on: 
  workflow_dispatch:

  
jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{secrets.TERRAFORM}}
      
      - name: Setup Go environment
        uses: actions/setup-go@v3.1.0
        with:
          go-version-file: "./go.mod"
          
      - name: Build Solution
        run: "env GOOS=linux GOARCH=amd64 go build -o output/main"

      - name: Terraform Init
        run: terraform init


      # On push to $default-branch, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          GITHUB_TOKEN: "${{secrets.TOKEN}}"
          TF_ACTION_WORKING_DIR: '.'
          AWS_ACCESS_KEY_ID:  "${{secrets.AWS_ACCESS_KEY_ID}}"
          AWS_SECRET_ACCESS_KEY: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_DEFAULT_OUTPUT: "json"
